apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices-spring-boot-3-microservice-network: "true"
        io.kompose.service: eureka-server
    spec:
      containers:
        - env:
            - name: eureka.client.fetch-registry
              value: "false"
            - name: eureka.client.register-with-eureka
              value: "false"
          image: hoangphucdvl/microservices-spring-boot-3-eureka-server:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/
            failureThreshold: 5
            periodSeconds: 15
            timeoutSeconds: 10
          name: eureka-server
          ports:
            - containerPort: 8761
              hostPort: 8761
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
