server:
  port: 8080
  http2:
    enabled: true

eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-services
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/authentication/**